prefix = "api"

[[queries]]
name = "Select Binary Data"
profile = "dev"
sql = "SELECT data_blob, data_bin from bin"
url = "bin"

[[queries]]
name = "Select Date, Time Data"
profile = "dev"
sql = "SELECT ts, datet from dt"
url = "date"


[[queries]]
name = "随便试试"
profile = "dev"
sql = "SELECT * from todos limit 100"
url = "todos"
